# This workflow validates the document for markup and examples.
name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Build and Validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: bundle install

    # Validate Examples
    - name: Verify examples are consistent
      run: bundle exec rake test

    # Check HTML5 (obsoleted by ReSpec, eventually)
    - name: Checks HTML5
      run: bundle exec rake check_html

    # Validate via ReSpec
    # See https://github.com/w3c/spec-prod/blob/main/docs/examples.md
    #- name: ReSpec Checker
    #  uses: w3c/spec-prod@v1
    #  with:
    #    VALIDATE_LINKS: true
    #    VALIDATE_MARKUP: true
